export async function GET(request) {
  try {
    const { searchParams } = new URL(request.url);
    const reportDataParam = searchParams.get("data");

    if (!reportDataParam) {
      return Response.json({ error: "Report data is required" }, { status: 400 });
    }

    let reportData;
    try {
      reportData = JSON.parse(decodeURIComponent(reportDataParam));
    } catch {
      return Response.json({ error: "Invalid report data" }, { status: 400 });
    }

    // Generate PDF using simple HTML-to-PDF approach
    const htmlContent = generateReportHTML(reportData);

    // Since puppeteer may not be available in all environments,
    // return HTML content that can be converted client-side with jsPDF + html2canvas
    return new Response(htmlContent, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
      },
    });
  } catch (error) {
    console.error("Report download error:", error);
    return Response.json({ error: "Failed to generate PDF" }, { status: 500 });
  }
}

function generateReportHTML(data) {
  const sections = data.sections || [];
  const generatedAt = new Date(data.generatedAt || Date.now()).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Inter', sans-serif;
    background: #ffffff;
    color: #1a1a2e;
    padding: 48px;
    max-width: 800px;
    margin: 0 auto;
    line-height: 1.7;
  }
  .header {
    border-bottom: 3px solid #7c3aed;
    padding-bottom: 24px;
    margin-bottom: 32px;
  }
  .header h1 {
    font-size: 28px;
    font-weight: 700;
    color: #7c3aed;
    margin-bottom: 8px;
  }
  .header .meta {
    font-size: 13px;
    color: #64748b;
  }
  .header .company {
    font-size: 14px;
    color: #1a1a2e;
    font-weight: 600;
    margin-bottom: 4px;
  }
  .section {
    margin-bottom: 28px;
  }
  .section h2 {
    font-size: 18px;
    font-weight: 600;
    color: #7c3aed;
    margin-bottom: 12px;
    padding-bottom: 8px;
    border-bottom: 1px solid #e2e8f0;
  }
  .section p {
    font-size: 14px;
    color: #334155;
    margin-bottom: 12px;
  }
  .footer {
    border-top: 1px solid #e2e8f0;
    padding-top: 16px;
    margin-top: 32px;
    font-size: 11px;
    color: #94a3b8;
    text-align: center;
  }
</style>
</head>
<body>
  <div class="header">
    <div class="company">MyMoneyPlant — Wealth Management</div>
    <h1>${data.reportType ? data.reportType.charAt(0).toUpperCase() + data.reportType.slice(1) : "Financial"} Report</h1>
    <div class="meta">Period: ${data.period || "N/A"} | Generated: ${generatedAt}</div>
  </div>
  ${sections.map((s) => `
  <div class="section">
    <h2>${s.title}</h2>
    ${s.content.split("\n").filter(Boolean).map((p) => `<p>${p}</p>`).join("")}
  </div>`).join("")}
  <div class="footer">
    This report was generated by MyMoneyPlant AI. Data sourced from market feeds and portfolio analytics.
    <br>Confidential — for authorized recipients only.
  </div>
</body>
</html>`;
}
